#!/bin/bash
set -euo pipefail
DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

WASM_OUT=$(bazel build //wasm:wasm 2>&1 | grep "bazel-out/" | xargs)

OUT="$(mktemp -d)"
function cleanup {
  rm -rf "$OUT"
}
trap cleanup EXIT

cp $WASM_OUT $OUT/asteroids.wasm
cp $(go env GOROOT)/misc/wasm/wasm_exec.js $OUT/
cp $DIR/index.html $OUT/

REMOTE=$(git remote get-url origin)
COMMIT=$(git rev-parse HEAD)
cd $OUT
git init .
git remote add origin $REMOTE
git checkout -b gh-pages
git add .
git commit -m "Autogenerated gh-pages from $COMMIT"
git push origin gh-pages --force
